// This file is generated by generator.ts

import Foundation

public class TTS {

  private let networkClient: NetworkClient

  init(networkClient: NetworkClient) {
    self.networkClient = networkClient
  }

  public func synthesizeJson(
    request: PostedTts,
    timeoutDuration: TimeInterval = 120,
    maxRetries: Int = 0
  ) async throws -> ReturnTts {
    return try await networkClient.send(
      Endpoint.synthesizeJson(
        request: request,
        timeoutDuration: timeoutDuration,
        maxRetries: maxRetries)
    )
  }

  public func synthesizeFile(
    request: PostedTts,
    timeoutDuration: TimeInterval = 120,
    maxRetries: Int = 0
  ) async throws -> Data {
    return try await networkClient.send(
      Endpoint.synthesizeFile(
        request: request,
        timeoutDuration: timeoutDuration,
        maxRetries: maxRetries)
    )
  }

  public func synthesizeFileStreaming(
    request: PostedTts,
    timeoutDuration: TimeInterval = 300,
    maxRetries: Int = 0
  ) -> AsyncThrowingStream<Data, Error> {
    return networkClient.stream(
      Endpoint.synthesizeFileStream(
        request: request,
        timeoutDuration: timeoutDuration,
        maxRetries: maxRetries)
    )
  }

  public func synthesizeJsonStreaming(
    request: PostedTts,
    timeoutDuration: TimeInterval = 300,
    maxRetries: Int = 0
  ) -> AsyncThrowingStream<SnippetAudioChunk, Error> {
    return networkClient.stream(
      Endpoint.synthesizeJsonStream(
        request: request,
        timeoutDuration: timeoutDuration,
        maxRetries: maxRetries)
    )
  }
}

// MARK: - Endpoint Definitions
extension Endpoint where Response == ReturnTts {
  fileprivate static func synthesizeJson(
    request: PostedTts,
    timeoutDuration: TimeInterval,
    maxRetries: Int
  ) -> Endpoint<ReturnTts> {
    Endpoint(
      path: "/v0/tts",
      method: .post,
      headers: ["Content-Type": "application/json"],
      body: request,
      cachePolicy: .reloadIgnoringLocalAndRemoteCacheData,
      timeoutDuration: timeoutDuration,
      maxRetries: maxRetries)
  }
}

extension Endpoint where Response == Data {
  fileprivate static func synthesizeFile(
    request: PostedTts,
    timeoutDuration: TimeInterval,
    maxRetries: Int
  ) -> Endpoint<Data> {
    Endpoint(
      path: "/v0/tts/file",
      method: .post,
      headers: ["Content-Type": "application/json"],
      body: request,
      cachePolicy: .reloadIgnoringLocalAndRemoteCacheData,
      timeoutDuration: timeoutDuration,
      maxRetries: maxRetries)
  }
}

extension Endpoint where Response == Data {
  fileprivate static func synthesizeFileStream(
    request: PostedTts,
    timeoutDuration: TimeInterval,
    maxRetries: Int
  ) -> Endpoint<Data> {
    return Endpoint(
      path: "/v0/tts/stream/file",
      method: .post,
      headers: ["Content-Type": "application/json"],
      body: request,
      cachePolicy: .reloadIgnoringLocalAndRemoteCacheData,
      timeoutDuration: timeoutDuration,
      maxRetries: maxRetries
    )
  }
}

extension Endpoint where Response == SnippetAudioChunk {
  fileprivate static func synthesizeJsonStream(
    request: PostedTts,
    timeoutDuration: TimeInterval,
    maxRetries: Int
  ) -> Endpoint<SnippetAudioChunk> {
    return Endpoint(
      path: "/v0/tts/stream/json",
      method: .post,
      headers: ["Content-Type": "application/json"],
      body: request,
      cachePolicy: .reloadIgnoringLocalAndRemoteCacheData,
      timeoutDuration: timeoutDuration,
      maxRetries: maxRetries
    )
  }
}
